import {
  faClock,
  faCalendar,
  faBell,
} from "@fortawesome/free-regular-svg-icons";
import {
  faPhone,
  faUpRightAndDownLeftFromCenter,
  faDownLeftAndUpRightToCenter,
  faStar,
  faCommentDots,
  faHeart,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import { status, TCardData } from "../types/TCardData";
export type TCardName = {
  setSelectedName: (name: string) => void;
};
export const CardData: TCardData[] = [
  {
    id: 1,
    imageUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    name: "Sarah",
    age: 32,
    gender: "Female",
    status: status.AvailableNow,
    icons: {
      iconClock: faClock,
      iconPhone: faPhone,
      iconBell: faBell,
      iconArrowUp: faUpRightAndDownLeftFromCenter,
      iconArrowDown: faDownLeftAndUpRightToCenter,
      iconStar: faStar,
      iconSessions: faCommentDots,
      iconHeart: faHeart,
      iconUser: faUser,
      iconCalender: faCalendar,
    },
    tags: ["anxiety", "work-stress", "relationships"],
    summary: "Compassionate listener with a multicultural background.",
    details:
      "Experinced counselor specializing in life transitions and family dynamics. My approach is practical and soultion-focues.",
    rating: "4.9/5",
    sessions: "250+",
    helped: "180+",
    returnRate: "85%",
    languages: ["English", "French", "British English", "Canadian French"],
    available: [
      "Mon:9AM-5PM",
      "Tue:9AM-5PM",
      "Wed:9AM-5PM",
      "Thu:9AM-5PM",
      "Fri:9AM-5PM",
    ],
  },
  {
    id: 2,
    imageUrl: "https://randomuser.me/api/portraits/men/12.jpg",
    name: "Michael",
    age: 45,
    gender: "Male",
    status: status.Weekend,
    icons: {
      iconClock: faClock,
      iconBell: faBell,
      iconArrowUp: faUpRightAndDownLeftFromCenter,
      iconArrowDown: faDownLeftAndUpRightToCenter,
      iconStar: faStar,
      iconSessions: faCommentDots,
      iconHeart: faHeart,
      iconUser: faUser,
      iconCalender: faCalendar,
    },

    tags: ["depression", "career-changes", "family-issues"],
    summary: "Compassionate listener with a multicultural background.",
    details:
      "Experinced counselor specializing in life transitions and family dynamics. My approach is practical and soultion-focues.",
    rating: "4.9/5",
    sessions: "250+",
    helped: "180+",
    returnRate: "85%",
    languages: ["English", "French", "British English", "Canadian French"],
    available: [
      "Mon:9AM-5PM",
      "Tue:9AM-5PM",
      "Wed:9AM-5PM",
      "Thu:9AM-5PM",
      "Fri:9AM-5PM",
    ],
  },
  {
    id: 3,
    imageUrl: "https://randomuser.me/api/portraits/women/3.jpg",
    name: "Aisha",
    age: 28,
    gender: "Female",
    status: status.ClosedNow,
    icons: {
      iconClock: faClock,
      iconBell: faBell,
      iconArrowUp: faUpRightAndDownLeftFromCenter,
      iconArrowDown: faDownLeftAndUpRightToCenter,
      iconStar: faStar,
      iconSessions: faCommentDots,
      iconHeart: faHeart,
      iconUser: faUser,
      iconCalender: faCalendar,
    },
    tags: ["self-esteem", "cultural-identity", "relationships"],
    summary: "Compassionate listener with a multicultural background.",
    details:
      "Experinced counselor specializing in life transitions and family dynamics. My approach is practical and soultion-focues.",
    rating: "4.9/5",
    sessions: "250+",
    helped: "180+",
    returnRate: "85%",
    languages: ["English", "French", "British English", "Canadian French"],
    available: [
      "Mon:9AM-5PM",
      "Tue:9AM-5PM",
      "Wed:9AM-5PM",
      "Thu:9AM-5PM",
      "Fri:9AM-5PM",
    ],
  },
  {
    id: 4,
    imageUrl: "https://randomuser.me/api/portraits/men/9.jpg",
    name: "Raj",
    age: 35,
    gender: "Male",
    status: status.AvailableNow,
    icons: {
      iconClock: faClock,
      iconPhone: faPhone,
      iconArrowUp: faUpRightAndDownLeftFromCenter,
      iconArrowDown: faDownLeftAndUpRightToCenter,
      iconStar: faStar,
      iconSessions: faCommentDots,
      iconHeart: faHeart,
      iconUser: faUser,
      iconCalender: faCalendar,
    },

    tags: ["focused", "communication", "career-changes"],
    summary: "Compassionate listener with a multicultural background.",
    details:
      "Experinced counselor specializing in life transitions and family dynamics. My approach is practical and soultion-focues.",
    rating: "4.9/5",
    sessions: "250+",
    helped: "180+",
    returnRate: "85%",
    languages: ["English", "French", "British English", "Canadian French"],
    available: [
      "Mon:9AM-5PM",
      "Tue:9AM-5PM",
      "Wed:9AM-5PM",
      "Thu:9AM-5PM",
      "Fri:9AM-5PM",
    ],
  },
  {
    id: 5,
    imageUrl: "https://randomuser.me/api/portraits/women/23.jpg",
    name: "Emma",
    age: 29,
    gender: "Female",
    status: status.Weekend,
    icons: {
      iconClock: faClock,
      iconBell: faBell,
      iconArrowUp: faUpRightAndDownLeftFromCenter,
      iconArrowDown: faDownLeftAndUpRightToCenter,
      iconStar: faStar,
      iconSessions: faCommentDots,
      iconHeart: faHeart,
      iconUser: faUser,
      iconCalender: faCalendar,
    },
    tags: ["compassionate", "anxiety", "relationships"],
    summary: "Compassionate listener with a multicultural background.",
    details:
      "Experinced counselor specializing in life transitions and family dynamics. My approach is practical and soultion-focues.",
    rating: "4.9/5",
    sessions: "250+",
    helped: "180+",
    returnRate: "85%",
    languages: ["English", "French", "British English", "Canadian French"],
    available: [
      "Mon:9AM-5PM",
      "Tue:9AM-5PM",
      "Wed:9AM-5PM",
      "Thu:9AM-5PM",
      "Fri:9AM-5PM",
    ],
  },
  {
    id: 6,
    imageUrl: "https://randomuser.me/api/portraits/men/41.jpg",
    name: "Carlos",
    age: 41,
    gender: "Female",
    status: status.AvailableNow,
    icons: {
      iconClock: faClock,
      iconPhone: faPhone,
      iconArrowUp: faUpRightAndDownLeftFromCenter,
      iconArrowDown: faDownLeftAndUpRightToCenter,
      iconStar: faStar,
      iconSessions: faCommentDots,
      iconHeart: faHeart,
      iconUser: faUser,
      iconCalender: faCalendar,
    },
    tags: ["culture", "family-issues", "culture-identity"],
    summary: "Compassionate listener with a multicultural background.",
    details:
      "Experinced counselor specializing in life transitions and family dynamics. My approach is practical and soultion-focues.",
    rating: "4.9/5",
    sessions: "250+",
    helped: "180+",
    returnRate: "85%",
    languages: ["English", "French", "British English", "Canadian French"],
    available: [
      "Mon:9AM-5PM",
      "Tue:9AM-5PM",
      "Wed:9AM-5PM",
      "Thu:9AM-5PM",
      "Fri:9AM-5PM",
    ],
  },
];
